[tool.poetry]
name = "gvr"
version = "0.1.0"
description = ""
authors = ["Ian McCormack <icmccorm@andrew.cmu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
